init:
  - git config --global core.autocrlf input
version: 0.{build}
branches:
  except:
  - gh-pages
build_script:
  - cmd: build.cmd
test: off
artifacts:
- path: '**\*.svclog'
  name: logs
- path: '**\*.log'
  name: logs
- path: '**\test\*\logs'
  name: logs
- path: 'release\nuget\*.nupkg'
  name: nuget
deploy: off
